export const CardSliderItems = [
    {
        id: 6,
        image: 'diagnostico_directo/generador_pulsos_inyectores',
        title: 'Generador de Pulsos d...',
        price: 15136,
        type: 'Diagnostico Directo',
    },
    {
        id: 11,
        image: 'diagnostico_directo/punta_logica',
        title: 'Punta Lógica',
        price: 4400,
        type: 'Diagnostico Directo',
    },
    {
        id: 16,
        image: 'escaneres/escaner_autolink_AL529',
        title: 'Escaner Autolink AL529HD',
        price: 31821,
        type: 'Escaner',
    },
    {
        id: 17,
        image: 'escaneres/escaner_maxidiag_Md808',
        title: 'Escaner Maxidiag Md808 Pro',
        price: 58132,
        type: 'Escaner',
    },
    {
        id: 21,
        image: 'escaneres_profesionales/maxiSys_MS906',
        title: 'MaxiSys MS906',
        price: 240000,
        type: 'Escaner Profesional',
    },
    {
        id: 26,
        image: 'gnc/carburada_ZL-7',
        title: 'Carburada (ZL-7)',
        price: 4536,
        type: 'Gnc',
    },
    {
        id: 56,
        image: 'tacometro/tacometro_digital_DT6236',
        title: 'Tacometro Digital DT6236',
        price: 3508,
        type: 'Tacometro',
    },
    {
        id: 62,
        image: 'testers/multimetro_digital_MY68T',
        title: 'Multimetro Digital MY68T',
        price: 4391,
        type: 'Testers',
    },
]