export const CardAllItems = [
    {
        id: 1,
        image: 'bateas_ultrasonidos/batea_ultrasonica_baku_serie_Dadi',
        title: 'Batea Ultrasonica Baku Serie Dadi 6 Litros Inoxidable',
        price: '62.900,00',
        type: 'Batea',
    },
    {
        id: 2,
        image: 'bateas_ultrasonidos/batea_ultrasonido_baku_modelo_2000',
        title: 'Batea De Ultrasonido Baku Modelo 2000',
        price: '30.317,00',
        type: 'Batea',
    },
    {
        id: 3,
        image: 'bateas_ultrasonidos/batea_ultrasonido_baku_modelo_Bk-3550',
        title: 'Batea De Ultrasonido Baku Modelo Bk-3550 Inoxidable',
        price: '9.250,00',
        type: 'Batea',
    },
    {
        id: 4,
        image: 'bateas_ultrasonidos/batea_ultrasonido_baku_modelo_Bk-9050',
        title: 'Batea De Ultrasonido Baku Modelo Bk-9050',
        price: '6.475,00',
        type: 'Batea',
    },
    {
        id: 5,
        image: 'diagnostico_directo/arranque_asistido_motores',
        title: 'Arranque Asistido de Motores',
        price: '15.692,00',
        type: 'Diagnostico Directo',
    },
    {
        id: 6,
        image: 'diagnostico_directo/generador_pulsos_inyectores',
        title: 'Generador de Pulsos de Inyectores',
        price: '15.136,00',
        type: 'Diagnostico Directo',
    },
    {
        id: 7,
        image: 'diagnostico_directo/motor_virtual',
        title: 'Motor Virtual',
        price: '59.139,00',
        type: 'Diagnostico Directo',
    },
    {
        id: 8,
        image: 'diagnostico_directo/osciloscopio_automotriz',
        title: 'Osciloscopio Automotriz',
        price: '28.400,00',
        type: 'Diagnostico Directo',
    },
    {
        id: 9,
        image: 'diagnostico_directo/probador_mariposas_motorizadas',
        title: 'Probador Mariposas Motorizadas',
        price: '22.176,00',
        type: 'Diagnostico Directo',
    },
    {
        id: 10,
        image: 'diagnostico_directo/probador_motores_paso_a_paso',
        title: 'Probador de Motores Paso a Paso',
        price: '4.400,00',
        type: 'Diagnostico Directo',
    },
    {
        id: 11,
        image: 'diagnostico_directo/punta_logica',
        title: 'Punta Lógica',
        price: '4.400,00',
        type: 'Diagnostico Directo',
    },
    {
        id: 12,
        image: 'diagnostico_directo/punta_logica_Autel_PS100',
        title: 'Punta Lógica Autel PS100',
        price: '18.000,00',
        type: 'Diagnostico Directo',
    },
    {
        id: 13,
        image: 'escaneres/escaner_autolink_329',
        title: 'Escaner Autolink 329',
        price: '9.282,00',
        type: 'Escaner',
    },
    {
        id: 14,
        image: 'escaneres/escaner_autolink_529',
        title: 'Escaner Autolink 529',
        price: '21.315,00',
        type: 'Escaner',
    },
    {
        id: 15,
        image: 'escaneres/escaner_autolink_539B',
        title: 'Escaner Autolink 539B',
        price: '32.104,00',
        type: 'Escaner',
    },
    {
        id: 16,
        image: 'escaneres/escaner_autolink_AL529',
        title: 'Escaner Autolink AL529HD',
        price: '31.821,00',
        type: 'Escaner',
    },
    {
        id: 17,
        image: 'escaneres/escaner_maxidiag_Md808',
        title: 'Escaner Maxidiag Md808 Pro',
        price: '58.132,00',
        type: 'Escaner',
    },
    {
        id: 18,
        image: 'escaneres/escanes_autolink_629',
        title: 'Escaner Autolink 629',
        price: '35.213,00',
        type: 'Escaner',
    },
    {
        id: 19,
        image: 'escaneres_profesionales/maxiCheck_MX808',
        title: 'MaxiCheck MX808',
        price: '78.000,00',
        type: 'Escaner Profesional',
    },
    {
        id: 20,
        image: 'escaneres_profesionales/maxisys_Cv',
        title: 'Maxisys Cv',
        price: '496.000,00',
        type: 'Escaner Profesional',
    },
    {
        id: 21,
        image: 'escaneres_profesionales/maxiSys_MS906',
        title: 'MaxiSys MS906',
        price: '240.000,00',
        type: 'Escaner Profesional',
    },
    {
        id: 22,
        image: 'escaneres_profesionales/maxiSys_MS906BT',
        title: 'MaxiSys MS906BT',
        price: '260.000,00',
        type: 'Escaner Profesional',
    },
    {
        id: 23,
        image: 'gnc/aspirada_de_nivel_ZL-5',
        title: 'Aspirada de Nivel (ZL-5)',
        price: '4.536,00',
        type: 'Gnc',
    },
    {
        id: 24,
        image: 'gnc/bobina_variable_ZA-6',
        title: 'Bobina Variable (ZA-6)',
        price: '6.300,00',
        type: 'Gnc',
    },
    {
        id: 25,
        image: 'gnc/bobina_ZA-3',
        title: 'Bobina (ZA-3)',
        price: '6.300,00',
        type: 'Gnc',
    },
    {
        id: 26,
        image: 'gnc/carburada_ZL-7',
        title: 'Carburada (ZL-7)',
        price: '4.536,00',
        type: 'Gnc',
    },
    {
        id: 27,
        image: 'gnc/control_Lambda_ZPP-1',
        title: 'Control Lambda (ZPP-1)',
        price: '8.500,00',
        type: 'Gnc',
    },
    {
        id: 28,
        image: 'gnc/control_LambdaBasico_ZPP-2',
        title: 'Control Lambda Básico (ZPP-2)',
        price: '6.300,00',
        type: 'Gnc',
    },
    {
        id: 29,
        image: 'gnc/digital_ZL-3',
        title: 'Digital (ZL-3)',
        price: '6.720,00',
        type: 'Gnc',
    },
    {
        id: 30,
        image: 'gnc/doble_señal_simple_ZA-8',
        title: 'Doble Señal Simple (ZA-8)',
        price: '6.300,00',
        type: 'Gnc',
    },
    {
        id: 31,
        image: 'gnc/electronica_de_nivel_ZL-1',
        title: 'Electrónica de Nivel (ZL-1)',
        price: '4.536,00',
        type: 'Gnc',
    },
    {
        id: 32,
        image: 'gnc/electronica_de_reserva_ZL-6',
        title: 'Electronica de Reserva (ZL-6)',
        price: '2.300,00',
        type: 'Gnc',
    },
    {
        id: 33,
        image: 'gnc/emulador_multipunto4Cilindros_ZE-5',
        title: 'Emulador Multipunto 4 Cilindros (ZE-5)',
        price: '4.620,00',
        type: 'Gnc',
    },
    {
        id: 34,
        image: 'gnc/inyeccion_SMD_ZL-8',
        title: 'Inyección SMD (ZL-8)',
        price: '4.536,00',
        type: 'Gnc',
    },
    {
        id: 35,
        image: 'gnc/inyeccion_ZL-2',
        title: 'Inyección (ZL-2)',
        price: '4.536,00',
        type: 'Gnc',
    },
    {
        id: 36,
        image: 'gnc/map_kangoo_ZA-7',
        title: 'MAP Kangoo (ZA-7)',
        price: '6.300,00',
        type: 'Gnc',
    },
    {
        id: 37,
        image: 'gnc/map_ZA-1',
        title: 'MAP (ZA-1)',
        price: '6.300,00',
        type: 'Gnc',
    },
    {
        id: 38,
        image: 'gnc/monoinyector_universal_ZE-3',
        title: 'Monoinyector Universal (ZE-3)',
        price: '3.150,00',
        type: 'Gnc',
    },
    {
        id: 39,
        image: 'gnc/monopunto_sonda_Lambda-Oxigeno_ZE-1',
        title: 'Monopunto Sonda Lambda/Oxígeno (ZE-1)',
        price: '4.500,00',
        type: 'Gnc',
    },
    {
        id: 40,
        image: 'gnc/multipunto_4Cil_SMD_Mercosur_ZE-7',
        title: 'Multipunto 4 Cil SMD Mercosur (ZE-7)',
        price: '4.620,00',
        type: 'Gnc',
    },
    {
        id: 41,
        image: 'gnc/multipunto_6Cilindros_ZE-6',
        title: 'Multipunto 6 Cilindros (ZE-6)',
        price: '5.880,00',
        type: 'Gnc',
    },
    {
        id: 42,
        image: 'gnc/señal_simple_ZA-5',
        title: 'Señal Simple (ZA-5)',
        price: '6.300,00',
        type: 'Gnc',
    },
    {
        id: 43,
        image: 'gnc/sistema_LambdaVolante_ZPP-3',
        title: 'Sistema Lambda Volante (ZPP-3)',
        price: '8.500,00',
        type: 'Gnc',
    },
    {
        id: 44,
        image: 'gnc/sonda_Lambda-Oxigeno_ZE-4',
        title: 'Sonda Lambda-Oxígeno (ZE-4)',
        price: '3.150,00',
        type: 'Gnc',
    },
    {
        id: 45,
        image: 'gnc/sonda_oxigeno_Regulable_ZE-11',
        title: 'Sonda Oxígeno Regulable (ZE-11)',
        price: '4.620,00',
        type: 'Gnc',
    },
    {
        id: 46,
        image: 'gnc/sonda_oxigeno_Regulable_ZE-11',
        title: 'Sonda Oxígeno Regulable (ZE-11)',
        price: '4.620,00',
        type: 'Gnc',
    },
    {
        id: 47,
        image: 'gnc/volante_ZA-2',
        title: 'Volante (ZA-2)',
        price: '6.300,00',
        type: 'Gnc',
    },
    {
        id: 48,
        image: 'portones_automaticos/plaqueta_porton_corredizo',
        title: 'Plaqueta Electrónica Universal Para Portón Corredizo Automático',
        price: '5.500,00',
        type: 'Porton',
    },
    {
        id: 49,
        image: 'portones_automaticos/plaqueta_porton_levadizos',
        title: 'Plaqueta Electrónica Universal Para Portón Levadizos Automático',
        price: '5.700,00',
        type: 'Porton',
    },
    {
        id: 50,
        image: 'proyectos_especiales/balanza_Digital_102',
        title: 'Balanza Digital 102',
        price: '?',
        type: 'Proyectos Especiales',
    },
    {
        id: 51,
        image: 'proyectos_especiales/balanza_Digital_103',
        title: 'Balanza Digital 103',
        price: '?',
        type: 'Proyectos Especiales',
    },
    {
        id: 52,
        image: 'proyectos_especiales/control_de_Nivel',
        title: 'Control de Nivel',
        price: '?',
        type: 'Proyectos Especiales',
    },
    {
        id: 53,
        image: 'proyectos_especiales/controlador_ambiental_C2',
        title: 'Controlador Ambiental C2',
        price: '?',
        type: 'Proyectos Especiales',
    },
    {
        id: 54,
        image: 'proyectos_especiales/controlador_ambiental_C5',
        title: 'Controlador Ambiental C5',
        price: '?',
        type: 'Proyectos Especiales',
    },
    {
        id: 55,
        image: 'proyectos_especiales/encendido_Electrónico',
        title: 'Encendido Electrónico',
        price: '?',
        type: 'Proyectos Especiales',
    },
    {
        id: 56,
        image: 'proyectos_especiales/sistema_Bi-Fuel',
        title: 'Sistema Bi-Fuel',
        price: '?',
        type: 'ProyectosEspeciales',
    },
    {
        id: 57,
        image: 'tacometro/tacometro_digital_DT6236',
        title: 'Tacometro Digital DT6236',
        price: '3.508,00',
        type: 'Tacometro',
    },
    {
        id: 58,
        image: 'testers/multimetro_digital_DT33A',
        title: 'Multimetro Digital DT33A',
        price: '1.171,00',
        type: 'Testers',
    },
    {
        id: 59,
        image: 'testers/multimetro_digital_DT182',
        title: 'Multimetro Digital DT182',
        price: '680,00',
        type: 'Testers',
    },
    {
        id: 60,
        image: 'testers/multimetro_digital_DT203B',
        title: 'Multimetro Digital DT203B',
        price: '3.552,00',
        type: 'Testers',
    },
    {
        id: 61,
        image: 'testers/multimetro_digital_DT9065',
        title: 'Multimetro Digital DT9065',
        price: '8.130,00',
        type: 'Testers',
    },
    {
        id: 62,
        image: 'testers/multimetro_digital_M890C',
        title: 'Multimetro Digital M890C',
        price: '1.481,00',
        type: 'Testers',
    },
    {
        id: 63,
        image: 'testers/multimetro_digital_MY68T',
        title: 'Multimetro Digital MY68T',
        price: '4.391,00',
        type: 'Testers',
    },
    {
        id: 64,
        image: 'testers/multimetro_digital_VC9802',
        title: 'Multimetro Digital VC9802',
        price: '2.197,00',
        type: 'Testers',
    },
]