export const CardSliderItems = [
    {
        id: 1,
        image: 'escaneres_profesionales/maxiCheck_MX808',
        title: 'MaxiCheck MX808',
        price: '78.000,00',
        type: 'Escaner Profesional',
    },
    {
        id: 2,
        image: 'escaneres_profesionales/maxisys_Cv',
        title: 'Maxisys Cv',
        price: '496.000,00',
        type: 'Escaner Profesional',
    },
    {
        id: 3,
        image: 'escaneres_profesionales/maxiSys_MS906',
        title: 'MaxiSys MS906',
        price: '240.000,00',
        type: 'Escaner Profesional',
    },
    {
        id: 4,
        image: 'escaneres_profesionales/maxiSys_MS906BT',
        title: 'MaxiSys MS906BT',
        price: '260.000,00',
        type: 'Escaner Profesional',
    },
    {
        id: 5,
        image: 'gnc/aspirada_de_nivel_ZL-5',
        title: 'Aspirada de Nivel (ZL-5)',
        price: '4.536,00',
        type: 'Gnc',
    },
    {
        id: 6,
        image: 'gnc/bobina_variable_ZA-6',
        title: 'Bobina Variable (ZA-6)',
        price: '6.300,00',
        type: 'Gnc',
    },
    {
        id: 7,
        image: 'gnc/bobina_ZA-3',
        title: 'Bobina (ZA-3)',
        price: '6.300,00',
        type: 'Gnc',
    },
    {
        id: 8,
        image: 'gnc/carburada_ZL-7',
        title: 'Carburada (ZL-7)',
        price: '4.536,00',
        type: 'Gnc',
    },
]